version: "3.8"

services:
  tileserver:
    build: .
    container_name: tileserver
    working_dir: /data
    volumes:
      - ../../data:/data
    ports:
      - "8080:80"
    command: >
      tileserver-gl --port 80 --public /data/factory.mbtiles
