version: '3.8'

services:
  # Backend API
  react_app_factory_map_backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: React_App_Factory_Map_Backend
    environment:
      - DEV_MODE=true
      - PG_HOST=postgres_c
      - PG_USER=postgres
      - PG_PASSWORD=martinmi
      - PG_DB=layout_proizvodnja_libre_konva
    ports:
      - "7998:7998"
    depends_on:
      - postgres_c
    networks:
      - postgres_network
    restart: unless-stopped
    volumes:
      - ./app/backend:/app:rw  # Mount backend source for development
      - /app/__pycache__  # Anonymous volume to preserve Python cache

  # Frontend (Development)
  react_app_factory_map_frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    container_name: React_App_Factory_Map_Frontend
    ports:
      - "5173:5173"  # Vite dev server port
    depends_on:
      - backend
    networks:
      - postgres_network
    restart: unless-stopped
    volumes:
      - ./app/frontend:/app:rw  # Mount frontend source for development
      - /app/node_modules  # Anonymous volume to preserve node_modules


networks:
  postgres_network:
    driver: bridge
